# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zhaopeng/Desktop/毕设/application/QT_Ui/exer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_exer(object):
    def setupUi(self, MainWindow_exer):
        MainWindow_exer.setObjectName("MainWindow_exer")
        MainWindow_exer.resize(833, 639)
        MainWindow_exer.setMinimumSize(QtCore.QSize(800, 580))
        self.centralwidget = QtWidgets.QWidget(MainWindow_exer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(800, 580))
        self.frame.setStyleSheet("#frame{\n"
"    border:none;\n"
"    border-radius:20px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.158, y1:0, x2:0.842, y2:0.994, stop:0 rgba(251, 237, 150, 255), stop:0.881773 rgba(171, 236, 214, 255));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgba(255, 255, 255, 120);\n"
"    border:none;\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(50, 40))
        self.frame_5.setMaximumSize(QtCore.QSize(50, 40))
        self.frame_5.setStyleSheet("#frame_5{\n"
"    border:none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_back = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon)
        self.pushButton_back.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_3.addWidget(self.pushButton_back)
        self.horizontalLayout_4.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(120, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(120, 40))
        self.frame_4.setToolTipDuration(-1)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_max = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_max.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_max.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/maxsize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_max.setIcon(icon1)
        self.pushButton_max.setObjectName("pushButton_max")
        self.horizontalLayout_2.addWidget(self.pushButton_max)
        self.pushButton_dimi = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_dimi.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_dimi.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_dimi.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/diminish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dimi.setIcon(icon2)
        self.pushButton_dimi.setObjectName("pushButton_dimi")
        self.horizontalLayout_2.addWidget(self.pushButton_dimi)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_close.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon3)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_2.addWidget(self.pushButton_close)
        self.horizontalLayout_4.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(750, 480))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border:none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border:none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("#frame_8{\n"
"    border:none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(601, 102))
        self.frame_9.setMaximumSize(QtCore.QSize(1300, 400))
        self.frame_9.setStyleSheet("#frame_9{\n"
"    border:none;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color: rgb(186, 111, 36);\n"
"    background-color:rgba(255,255,255,115);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255,255,255,165);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_usual = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_usual.sizePolicy().hasHeightForWidth())
        self.pushButton_usual.setSizePolicy(sizePolicy)
        self.pushButton_usual.setMinimumSize(QtCore.QSize(110, 100))
        self.pushButton_usual.setMaximumSize(QtCore.QSize(110, 100))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(24)
        font.setItalic(True)
        self.pushButton_usual.setFont(font)
        self.pushButton_usual.setObjectName("pushButton_usual")
        self.horizontalLayout_5.addWidget(self.pushButton_usual)
        self.pushButton_catch = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_catch.setMinimumSize(QtCore.QSize(110, 100))
        self.pushButton_catch.setMaximumSize(QtCore.QSize(110, 100))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(24)
        font.setItalic(True)
        self.pushButton_catch.setFont(font)
        self.pushButton_catch.setObjectName("pushButton_catch")
        self.horizontalLayout_5.addWidget(self.pushButton_catch)
        self.pushButton_auto = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_auto.sizePolicy().hasHeightForWidth())
        self.pushButton_auto.setSizePolicy(sizePolicy)
        self.pushButton_auto.setMinimumSize(QtCore.QSize(110, 100))
        self.pushButton_auto.setMaximumSize(QtCore.QSize(110, 100))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(24)
        font.setItalic(True)
        self.pushButton_auto.setFont(font)
        self.pushButton_auto.setObjectName("pushButton_auto")
        self.horizontalLayout_5.addWidget(self.pushButton_auto)
        self.pushButton_center = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_center.setMinimumSize(QtCore.QSize(110, 100))
        self.pushButton_center.setMaximumSize(QtCore.QSize(110, 100))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(24)
        font.setItalic(True)
        self.pushButton_center.setFont(font)
        self.pushButton_center.setObjectName("pushButton_center")
        self.horizontalLayout_5.addWidget(self.pushButton_center)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    border:none;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow_exer.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_exer)
        self.pushButton_close.clicked.connect(MainWindow_exer.close) # type: ignore
        self.pushButton_dimi.clicked.connect(MainWindow_exer.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow_exer)

    def retranslateUi(self, MainWindow_exer):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_exer.setWindowTitle(_translate("MainWindow_exer", "MainWindow"))
        self.pushButton_usual.setText(_translate("MainWindow_exer", "常规测试"))
        self.pushButton_catch.setText(_translate("MainWindow_exer", "抓握训练"))
        self.pushButton_auto.setText(_translate("MainWindow_exer", "自主抓握"))
        self.pushButton_center.setText(_translate("MainWindow_exer", "center out"))
import res_rc
