# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zhaopeng/Desktop/毕设/application/QT_Ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(800, 580))
        self.frame.setMaximumSize(QtCore.QSize(800, 580))
        self.frame.setStyleSheet("#frame{\n"
"    border:none;\n"
"    border-radius:20px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.158, y1:0, x2:0.842, y2:0.994, stop:0 rgba(251, 237, 150, 255), stop:0.881773 rgba(171, 236, 214, 255));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border:none;\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"    background-color:rgba(255, 255, 255, 120)\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 12, 12, 12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_8.setMaximumSize(QtCore.QSize(200, 40))
        self.frame_8.setStyleSheet("#frame_8{\n"
"    border:none;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_line_horizontal = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setItalic(True)
        self.label_line_horizontal.setFont(font)
        self.label_line_horizontal.setStyleSheet("color: rgb(186, 111, 36);\n"
"border:none;\n"
"")
        self.label_line_horizontal.setObjectName("label_line_horizontal")
        self.verticalLayout_2.addWidget(self.label_line_horizontal)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("#frame_9{\n"
"    border:none;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(80, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(80, 40))
        self.frame_7.setStyleSheet("#frame_7{\n"
"    border:none;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_mini = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_mini.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_mini.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_mini.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_mini.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/zhaopeng/Desktop/毕设/application/QT_Ui/icons/diminish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mini.setIcon(icon)
        self.pushButton_mini.setObjectName("pushButton_mini")
        self.horizontalLayout_3.addWidget(self.pushButton_mini)
        self.pushButton_close = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_close.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/zhaopeng/Desktop/毕设/application/QT_Ui/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon1)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.horizontalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border:none;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    border:none;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_question = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_question.setGeometry(QtCore.QRect(170, 310, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(25)
        self.pushButton_question.setFont(font)
        self.pushButton_question.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 115);\n"
"    color:rgb(181,111,36);\n"
"    border:none;\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255, 255, 255, 160);\n"
"}")
        self.pushButton_question.setObjectName("pushButton_question")
        self.pushButton_exer = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_exer.setGeometry(QtCore.QRect(170, 180, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(25)
        self.pushButton_exer.setFont(font)
        self.pushButton_exer.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 115);\n"
"    color:rgb(181,111,36);\n"
"    border:none;\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255, 255, 255, 160);\n"
"}")
        self.pushButton_exer.setObjectName("pushButton_exer")
        self.label_line_vertical = QtWidgets.QLabel(self.frame_4)
        self.label_line_vertical.setGeometry(QtCore.QRect(30, 50, 31, 331))
        self.label_line_vertical.setStyleSheet("border:none;\n"
"border-left:2px solid rgba(186, 111, 36,255);")
        self.label_line_vertical.setText("")
        self.label_line_vertical.setObjectName("label_line_vertical")
        self.label_emoji_question = QtWidgets.QLabel(self.frame_4)
        self.label_emoji_question.setGeometry(QtCore.QRect(80, 310, 70, 70))
        self.label_emoji_question.setStyleSheet("image: url(:/icons/icons/material-symbols-light_feedback-outline-rounded.png);")
        self.label_emoji_question.setText("")
        self.label_emoji_question.setObjectName("label_emoji_question")
        self.pushButton_fun = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_fun.setGeometry(QtCore.QRect(170, 50, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Smiley Sans")
        font.setPointSize(25)
        self.pushButton_fun.setFont(font)
        self.pushButton_fun.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 115);\n"
"    color:rgb(181,111,36);\n"
"    border:none;\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(255, 255, 255, 160);\n"
"}")
        self.pushButton_fun.setObjectName("pushButton_fun")
        self.label_round_vline = QtWidgets.QLabel(self.frame_4)
        self.label_round_vline.setGeometry(QtCore.QRect(23, 40, 16, 16))
        self.label_round_vline.setStyleSheet("border:none;\n"
"border-radius:8px;\n"
"background-color: rgb(184, 111, 36);")
        self.label_round_vline.setText("")
        self.label_round_vline.setObjectName("label_round_vline")
        self.label_emoji_fun = QtWidgets.QLabel(self.frame_4)
        self.label_emoji_fun.setGeometry(QtCore.QRect(80, 50, 70, 70))
        self.label_emoji_fun.setStyleSheet("image: url(:/icons/icons/solar_emoji-funny-circle-broken.png);")
        self.label_emoji_fun.setText("")
        self.label_emoji_fun.setObjectName("label_emoji_fun")
        self.label_emoji_exercise = QtWidgets.QLabel(self.frame_4)
        self.label_emoji_exercise.setGeometry(QtCore.QRect(80, 180, 70, 70))
        self.label_emoji_exercise.setStyleSheet("image: url(:/icons/icons/material-symbols-light_exercise-outline.png);")
        self.label_emoji_exercise.setText("")
        self.label_emoji_exercise.setObjectName("label_emoji_exercise")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border:none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("#frame_5{\n"
"    border:none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_close.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_mini.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_line_horizontal.setText(_translate("MainWindow", "         天气图标  温度  日期"))
        self.pushButton_question.setText(_translate("MainWindow", "状况反馈"))
        self.pushButton_exer.setText(_translate("MainWindow", "康复训练"))
        self.pushButton_fun.setText(_translate("MainWindow", "趣味放松"))
import res_rc
