name: kraken
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pip:
      - mne==1.5.1
      - pydantic==2.4.2
      - pyedflib==0.1.36
      - pyserial==3.5
      - pytest==7.4.3
      - pyriemann==0.5
      - joblib==1.3.2
      - opencv_python~=4.8.1
      - numpy~=1.26
      - scipy~=1.11.3
      - scikit-learn~=1.3.2
      - matplotlib~=3.8.1
      - pyyaml~=6.0.1
      - hmmlearn~=0.3.0
